/* =========================================================
   SECU3 — Aides à l'apprentissage
   1. ASTUCES : un moyen mnémotechnique par question du contrôle
   2. BLOCS   : les 4 blocs de la méthode « 10 par 10 »
   3. BONUS   : questions d'entraînement DANS LE MÊME STYLE,
                sur les mêmes notions. Elles ne font PAS partie
                du contrôle de l'an dernier : elles servent à
                aller plus loin, et ne sont jamais mélangées aux 40.
   ========================================================= */

const ASTUCES = {
  1:"« 230 / 400 » : le petit chiffre est entre phase et neutre, le <b>grand</b> entre deux phases. Entre phases = <b>400</b>.",
  2:"50 Hz → 1 ÷ 50 = 0,02 s = <b>20 ms</b>. Le 2 de « 20 » vient de « 0,02 ».",
  3:"Le neutre est <b>bleu</b>, calme comme la mer. Vert/jaune = la terre (l’herbe).",
  4:"Un fusible <b>fond quand ça chauffe</b> : trop de courant = sur<b>intensité</b>.",
  5:"Contacteur = <b>contact</b> : il ouvre et ferme, il met en marche. Il ne protège pas.",
  6:"Le demi-cercle ressemble à un <b>aimant</b> qui attire le contact : c’est la bobine du <b>contacteur</b>.",
  7:"Petit <b>rond</b> = <b>interrupteur</b> (un « o » comme « on / off »).",
  8:"Forme <b>ronde</b> = magnétique = <b>court-circuit</b>.",
  9:"Forme <b>carrée</b> = <b>chaleur</b> = <b>surcharge</b>. « Carré, chaleur, charge. »",
  10:"À 30 mA on ne respire plus (paralysie respiratoire) → les prises sont protégées à <b>30 mA</b>.",
  11:"IP : 1<sup>er</sup> chiffre = solides, <b>2<sup>e</sup> chiffre = liquides</b>. « D’abord le sable, puis l’eau. »",
  12:"Minimum = <b>IP2x</b> : le chiffre 2, comme le 2<sup>e</sup> chiffre de la question d’avant.",
  13:"<b>10 mA</b> : 10 doigts qui se crispent, impossible de lâcher.",
  14:"Classe <b>2</b> = isolation <b>double</b>. 2 = double.",
  15:"63 kV, c’est énorme → la plus <b>grosse</b> catégorie : <b>HTB</b>. (HTA s’arrête à 50 kV.)",
  16:"Piège ! En <b>continu</b>, la TBT va jusqu’à 120 V. 100 V continu = <b>TBT</b>.",
  17:"TT : deux T = deux fois « <b>Terre</b> ». Les masses sont <b>obligatoirement</b> à la terre.",
  18:"TN : défaut = <b>court-circuit</b>, donc c’est le <b>disjoncteur</b> qui coupe.",
  19:"Humide = <b>25 V</b>. Sec = 50 V. L’eau divise par 2.",
  20:"Le titre vient du <b>patron</b> : <b>l’employeur</b>.",
  21:"BT = <b>30 cm</b>, à peine la longueur d’une règle d’école.",
  22:"Zone renforcée = il faut un vrai électricien : <b>BR</b> (R = Réparer).",
  23:"Toujours <b>couper le courant d’abord</b>, sinon tu deviens la 2<sup>e</sup> victime.",
  24:"Le seul choix <b>habilité BT</b> : <b>B1V</b>. H0, c’est la haute tension.",
  25:"Contre l’arc électrique, on protège tout le visage : <b>écran facial</b>.",
  26:"Travaux = chiffres <b>1 et 2</b> → <b>B2V</b>. Les lettres C, E, R ne font pas de travaux.",
  27:"<b>BR</b> = interventions géné<b>R</b>ales (R comme Réparer).",
  28:"BR = Réparer, donc <b>maintenance</b>. Consigner pour les autres, c’est le BC.",
  29:"<b>BS</b> = <b>S</b>imple = interventions <b>élémentaires</b>.",
  30:"Le BS fait des petites choses → le <b>plus petit</b> calibre : <b>32 A</b>.",
  31:"<b>BC</b> = <b>C</b>onsignation pour les autres.",
  32:"Le BR peut se consigner <b>lui-même</b> : <b>oui</b>.",
  33:"« <b>S</b>i <b>Ç</b>a <b>I</b>tère, <b>V</b>érifie <b>M</b>ieux » : Séparation, Condamnation, Identification, VAT, Mise à la terre.",
  34:"Seul le VAT fait une VAT → <b>aucun</b> des autres appareils.",
  35:"Classe A = le plus précis → la <b>plus petite</b> distance : <b>0,50 m</b>.",
  36:"Investigation = on cherche <b>loin</b> → la plus grande valeur : <b>50 m</b>.",
  37:"Zone d’<b>investigation</b> = on <b>analyse</b>. C’est la réponse la plus longue.",
  38:"Voisinage = lettre <b>V</b>. Le seul avec un V : <b>H0V</b>.",
  39:"Essais : le <b>BR</b> (encore lui) dans le cadre de ses interventions.",
  40:"Le plus petit des trois : <b>6 mm² cuivre</b>."
};

const BLOCS = [
  {id:'b1', t:'Bloc 1', sub:'Les chiffres et les symboles', ic:'🔢', from:1,  to:10},
  {id:'b2', t:'Bloc 2', sub:'IP, corps humain, tensions, régimes', ic:'🛡️', from:11, to:19},
  {id:'b3', t:'Bloc 3', sub:'Les habilitations', ic:'🪪', from:20, to:32},
  {id:'b4', t:'Bloc 4', sub:'Consignation et réseaux', ic:'🔒', from:33, to:40}
];

/* ── Questions bonus : même style, mêmes notions ─────────── */
const BONUS = [

/* Partie 1 — réseau et appareillage */
{c:'c1',t:'qcm',d:1,q:"On dispose d’un réseau triphasé 230 / 400 V. La tension efficace entre une phase et le neutre est de :",
 o:["230 V","400 V","230 × √3 V","400 × √2 V"], a:0,
 e:"Entre phase et neutre = tension <b>simple</b> = <b>230 V</b>. Entre deux phases = 400 V."},
{c:'c1',t:'qcm',d:1,q:"La fréquence du réseau EDF est de :",
 o:["50 Hz","60 Hz","100 Hz","20 Hz"], a:0,
 e:"En France (et en Europe), le réseau est à <b>50 Hz</b>, d’où la période de 20 ms. 60 Hz, c’est aux États-Unis."},
{c:'c1',t:'qcm',d:2,q:"Dans un réseau triphasé, la tension composée U et la tension simple V sont liées par :",
 o:["U = V × √3","U = V × √2","U = V / √3","U = 2 × V"], a:0,
 e:"<b>U = V × √3</b> : 230 × 1,73 ≈ 400 V."},
{c:'c1',t:'qcm',d:1,q:"D’après la norme NF C 15-100, la couleur du conducteur de protection (terre) est :",
 o:["Vert / jaune","Bleu","Noir","Marron"], a:0,
 e:"Le <b>vert/jaune</b> est réservé au conducteur de protection. Le bleu est réservé au neutre."},
{c:'c1',t:'qcm',d:1,q:"Quelle est la fonction d’un sectionneur ?",
 o:["Protéger contre les courts-circuits","Protéger contre les surcharges","Isoler un circuit de sa source","Interrompre ou mettre en service un circuit électrique"], a:2,
 e:"Le sectionneur <b>isole</b> un circuit de sa source (pour travailler dessus en sécurité). Il ne protège pas."},
{c:'c1',t:'qcm',d:2,q:"Un sectionneur se manœuvre :",
 o:["à vide (sans courant)","en charge","uniquement en cas de court-circuit"], a:0,
 e:"Le sectionneur n’a pas de pouvoir de coupure : on l’ouvre <b>à vide</b>, après avoir coupé la charge (sinon il y a un arc électrique)."},
{c:'c1',t:'qcm',d:1,q:"Quelle est la fonction d’un relais thermique ?",
 o:["Protéger contre les surcharges","Protéger contre les courts-circuits","Protéger contre les surtensions","Isoler un circuit de sa source"], a:0,
 e:"Le relais <b>thermique</b> chauffe lentement avec le courant : il détecte les <b>surcharges</b> (le symbole carré de la Q9)."},
{c:'c1',t:'qcm',d:1,q:"Un disjoncteur magnéto-thermique protège contre :",
 o:["les surcharges et les courts-circuits","les surtensions uniquement","les contacts directs uniquement"], a:0,
 e:"Partie <b>thermique</b> = surcharges, partie <b>magnétique</b> = courts-circuits. Les deux ensemble."},
{c:'c1',t:'qcm',d:2,q:"Sur le symbole d’un contact, une petite <b>croix</b> indique la fonction :",
 o:["Sectionneur","Contacteur","Interrupteur","Disjoncteur"], a:3,
 e:"Croix = <b>disjoncteur</b>. Demi-cercle = contacteur (Q6), rond = interrupteur (Q7), trait = sectionneur."},
{c:'c1',t:'qcm',d:2,q:"Sur le symbole d’un contact, un petit <b>trait perpendiculaire</b> indique la fonction :",
 o:["Sectionneur","Contacteur","Interrupteur","Disjoncteur"], a:0,
 e:"Trait = <b>sectionneur</b>."},
{c:'c1',t:'qcm',d:1,q:"Quel appareil protège une installation contre les surtensions (foudre) ?",
 o:["Le parafoudre","Le fusible","Le contacteur","Le sectionneur"], a:0,
 e:"Le <b>parafoudre</b>. Piège de la Q4 : le fusible protège contre les sur<b>intensités</b>, pas les sur<b>tensions</b>."},
{c:'c1',t:'qcm',d:2,q:"Le contacteur est commandé par :",
 o:["sa bobine","un bilame","une lame fusible"], a:0,
 e:"Quand on alimente la <b>bobine</b>, elle attire les contacts et le circuit se ferme. Le bilame est dans le relais thermique."},

/* Partie 2 — protection et domaines de tension */
{c:'c2',t:'qcm',d:1,q:"Une tension alternative de 400 V est située dans le domaine :",
 o:["HTA","HTB","BT","TBT"], a:2,
 e:"En alternatif, la BT va de 50 V à <b>1000 V</b> : 400 V = <b>BT</b>."},
{c:'c2',t:'qcm',d:1,q:"Une tension alternative de 20 kV est située dans le domaine :",
 o:["HTA","HTB","BT","TBT"], a:0,
 e:"De 1 kV à 50 kV en alternatif : <b>HTA</b>. 20 kV = HTA (c’est la tension des lignes de distribution)."},
{c:'c2',t:'qcm',d:1,q:"Une tension alternative de 24 V est située dans le domaine :",
 o:["HTA","HTB","BT","TBT"], a:3,
 e:"≤ 50 V en alternatif : <b>TBT</b>."},
{c:'c2',t:'qcm',d:2,q:"Une tension continue de 48 V est située dans le domaine :",
 o:["HTA","HTB","BT","TBT"], a:3,
 e:"En continu, la TBT va jusqu’à 120 V : 48 V continu = <b>TBT</b>."},
{c:'c2',t:'qcm',d:2,q:"Une tension alternative de 225 kV est située dans le domaine :",
 o:["HTA","HTB","BT","TBT"], a:1,
 e:"Plus de 50 kV en alternatif : <b>HTB</b> (lignes de transport)."},
{c:'c2',t:'qcm',d:1,q:"Dans un local sec, la tension alternative limite de sécurité est de :",
 o:["50 V","120 V","25 V","12 V"], a:0,
 e:"Local <b>sec</b> : <b>50 V</b>. Local humide : 25 V (Q19)."},
{c:'c2',t:'qcm',d:1,q:"Le degré de protection IP pour les corps solides est représenté par :",
 o:["le 1<sup>er</sup> chiffre","le 2<sup>ème</sup> chiffre","le 3<sup>ème</sup> chiffre"], a:0,
 e:"1<sup>er</sup> chiffre = <b>solides</b>, 2<sup>e</sup> chiffre = liquides (Q11)."},
{c:'c2',t:'qcm',d:1,q:"Pour quelle intensité d’un courant alternatif traversant le corps humain y a-t-il paralysie respiratoire :",
 o:["0,5 mA","10 mA","30 mA","1 mA"], a:2,
 e:"<b>30 mA</b> → paralysie respiratoire. C’est pour ça que les DDR des prises sont à 30 mA."},
{c:'c2',t:'qcm',d:2,q:"À partir de quelle intensité (alternatif) le courant est-il simplement <b>perçu</b> par le corps humain :",
 o:["0,5 mA","10 mA","30 mA","100 mA"], a:0,
 e:"Seuil de perception ≈ <b>0,5 mA</b>. Puis 10 mA contraction, 30 mA paralysie respiratoire."},
{c:'c2',t:'qcm',d:2,q:"Un DDR de sensibilité 30 mA protège avant tout :",
 o:["les personnes","les câbles contre les surcharges","l’installation contre la foudre"], a:0,
 e:"30 mA = haute sensibilité = protection des <b>personnes</b>. Les surcharges, c’est le disjoncteur."},
{c:'c2',t:'qcm',d:1,q:"Un appareil électrique de classe d’isolation 1 :",
 o:["a des masses métalliques qu’il faut relier à la terre","possède une isolation double","est alimenté en TBTS"], a:0,
 e:"Classe I = masses métalliques <b>à relier à la terre</b> (prise avec terre). Classe II = double isolation, classe III = TBTS."},
{c:'c2',t:'qcm',d:2,q:"Un appareil de classe d’isolation 3 est :",
 o:["alimenté en très basse tension de sécurité (TBTS)","relié obligatoirement à la terre","à double isolation"], a:0,
 e:"Classe III = alimenté en <b>TBTS</b>, la tension est si faible qu’elle n’est pas dangereuse."},
{c:'c2',t:'qcm',d:1,q:"En régime TT, quel est l’appareil qui assure la protection des personnes :",
 o:["le différentiel","le disjoncteur","l’interrupteur"], a:0,
 e:"En TT, le courant de défaut passe par la terre et reste faible : c’est le <b>différentiel</b> qui le détecte. En TN, c’est le disjoncteur (Q18)."},
{c:'c2',t:'qcm',d:2,q:"En régime TN, les masses métalliques de l’appareillage électrique sont reliées :",
 o:["au neutre","à une prise de terre séparée","à rien du tout"], a:0,
 e:"TN : 2<sup>e</sup> lettre <b>N</b> = masses reliées au <b>N</b>eutre."},
{c:'c2',t:'qcm',d:2,q:"En régime IT, le neutre est :",
 o:["isolé de la terre (ou relié par une forte impédance)","relié directement à la terre","relié aux masses"], a:0,
 e:"IT : <b>I</b> = neutre <b>I</b>solé. Utilisé quand on ne veut pas couper au premier défaut (hôpitaux, process continus)."},
{c:'c2',t:'qcm',d:1,q:"Le régime de neutre utilisé dans les habitations en France est :",
 o:["TT","TN","IT"], a:0,
 e:"Chez les particuliers : <b>TT</b>, d’où les différentiels 30 mA dans les tableaux."},
{c:'c2',t:'qcm',d:2,q:"Toucher une masse métallique mise accidentellement sous tension (défaut d’isolement) est un :",
 o:["contact indirect","contact direct","court-circuit"], a:0,
 e:"Masse sous tension par défaut = <b>contact indirect</b>. Toucher directement un fil nu = contact direct."},

/* Partie 3 — habilitations et zones */
{c:'c3',t:'qcm',d:1,q:"Dans le symbole d’habilitation, la lettre <b>H</b> désigne :",
 o:["les ouvrages HTA et HTB","les ouvrages BT et TBT","les travaux hors tension"], a:0,
 e:"<b>B</b> = basse tension (BT et TBT), <b>H</b> = haute tension (HTA et HTB)."},
{c:'c3',t:'qcm',d:1,q:"Dans le symbole d’habilitation, le chiffre <b>2</b> (B2, H2) désigne :",
 o:["un chargé de travaux","un exécutant","un non-électricien"], a:0,
 e:"<b>1</b> = exécutant, <b>2</b> = <b>chargé de travaux</b>, 0 = non-électricien."},
{c:'c3',t:'qcm',d:1,q:"Dans le symbole d’habilitation, le chiffre <b>1</b> (B1, H1) désigne :",
 o:["un exécutant","un chargé de travaux","un chargé de consignation"], a:0,
 e:"<b>1</b> = <b>exécutant</b> : il travaille sous les ordres d’un chargé de travaux (2)."},
{c:'c3',t:'qcm',d:1,q:"L’attribut <b>V</b> (B1V, B2V, H0V) signifie :",
 o:["autorisé au voisinage","travail sous tension","vérification"], a:0,
 e:"<b>V</b> = <b>voisinage</b> : la personne peut travailler à proximité de pièces nues sous tension."},
{c:'c3',t:'qcm',d:1,q:"Une habilitation <b>B0</b> permet :",
 o:["des opérations d’ordre non électrique","des interventions générales","des consignations"], a:0,
 e:"<b>0</b> = travaux <b>non électriques</b> (peintre, maçon… dans un local électrique)."},
{c:'c3',t:'qcm',d:1,q:"Qui peut réaliser des essais, mesurages et vérifications ?",
 o:["BE","BS","B0"], a:0,
 e:"<b>BE</b> = <b>E</b>ssais, mesurages, vérifications."},
{c:'c3',t:'qcm',d:1,q:"Le BS peut-il faire des travaux ?",
 o:["Oui","Non"], a:1,
 e:"<b>Non</b> : le BS fait seulement des interventions élémentaires. Les travaux sont pour les indices 1 et 2."},
{c:'c3',t:'qcm',d:2,q:"La zone de voisinage renforcé BT (zone 4) s’étend :",
 o:["de la pièce nue sous tension jusqu’à 0,30 m","de 0,30 m à 3 m","au-delà de 3 m"], a:0,
 e:"Zone 4 = entre la pièce nue et la <b>DMA de 0,30 m</b>."},
{c:'c3',t:'qcm',d:2,q:"Il est recommandé de faire le recyclage de l’habilitation électrique tous les :",
 o:["3 ans","10 ans","6 mois"], a:0,
 e:"Recyclage recommandé tous les <b>3 ans</b>. Le titre est aussi revu si on change de poste ou d’employeur."},
{c:'c3',t:'qcm',d:1,q:"Un titre d’habilitation obtenu chez un employeur est-il valable chez un nouvel employeur ?",
 o:["Non, c’est le nouvel employeur qui le délivre","Oui, à vie","Oui, pendant 3 ans"], a:0,
 e:"C’est <b>l’employeur</b> qui délivre le titre (Q20). Nouvel employeur = nouveau titre."},
{c:'c3',t:'qcm',d:1,q:"Une électrocution est :",
 o:["une électrisation qui entraîne la mort","une simple sensation de picotement","une brûlure sans gravité"], a:0,
 e:"Électrisation = le courant traverse le corps. <b>Électrocution</b> = électrisation <b>mortelle</b>."},
{c:'c3',t:'qcm',d:1,q:"Après avoir mis le circuit hors tension face à un électrisé, on :",
 o:["alerte les secours (15, 18 ou 112)","quitte les lieux","remet le courant pour vérifier"], a:0,
 e:"1. Couper (Q23) → 2. <b>Alerter</b> (15, 18, 112) → 3. Secourir."},
{c:'c3',t:'qcm',d:2,q:"Des gants isolants de <b>classe 0</b> protègent jusqu’à :",
 o:["1000 V en alternatif","50 V en alternatif","20 kV"], a:0,
 e:"Classe 0 = jusqu’à <b>1000 V</b> alternatif, c’est-à-dire toute la BT. C’est pour ça qu’on les porte en zone 4 (Q25)."},
{c:'c3',t:'qcm',d:2,q:"L’écran facial porté en zone 4 protège surtout contre :",
 o:["l’arc électrique (flash, projections)","le bruit","la poussière"], a:0,
 e:"L’<b>arc électrique</b> produit un flash UV très intense et des projections de métal fondu."},

/* Partie 4 — consignation et VAT */
{c:'c4',t:'qcm',d:1,q:"Quelle est la <b>première</b> étape de la consignation ?",
 o:["La séparation","La VAT","La condamnation","La mise à la terre"], a:0,
 e:"On commence par <b>séparer</b> (ouvrir le circuit). Ordre : S, C, I, V, M."},
{c:'c4',t:'qcm',d:1,q:"Quelle est la <b>dernière</b> étape de la consignation ?",
 o:["La mise à la terre et en court-circuit","La condamnation","L’identification","La séparation"], a:0,
 e:"On finit par la <b>mise à la terre et en court-circuit</b> (si nécessaire), juste après la VAT."},
{c:'c4',t:'qcm',d:1,q:"La condamnation consiste à :",
 o:["bloquer l’appareil de séparation en position ouverte (cadenas) et le signaler (pancarte)","vérifier l’absence de tension","relier les conducteurs à la terre"], a:0,
 e:"Condamner = <b>cadenas + pancarte</b>, pour que personne ne remette le courant."},
{c:'c4',t:'qcm',d:2,q:"Juste avant de faire la VAT, on fait :",
 o:["l’identification","la séparation","la mise à la terre"], a:0,
 e:"S, C, <b>I</b>, V, M : l’<b>identification</b> vient juste avant la VAT."},
{c:'c4',t:'qcm',d:2,q:"Le VAT (vérificateur d’absence de tension) doit être testé :",
 o:["avant et après la vérification","seulement après","jamais, il est fiable"], a:0,
 e:"On teste le VAT <b>avant</b> (pour savoir s’il marche) et <b>après</b> (pour être sûr qu’il n’est pas tombé en panne pendant)."},
{c:'c4',t:'qcm',d:2,q:"La VAT se fait sur :",
 o:["tous les conducteurs actifs, neutre compris","uniquement la phase","uniquement le neutre"], a:0,
 e:"<b>Tous</b> les conducteurs actifs, y compris le <b>neutre</b>, qui peut être sous tension en cas de défaut."},
{c:'c4',t:'qcm',d:1,q:"Qui consigne un ouvrage pour une équipe qui va faire des travaux ?",
 o:["Le chargé de consignation (BC)","L’exécutant (B1)","Le non-électricien (B0)"], a:0,
 e:"Consigner pour les autres = <b>BC</b>, le chargé de consignation."}
];
